# Generated by Django 4.0.1 on 2022-04-28 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='book/files/audio/')),
                ('img', models.ImageField(upload_to='book/image/')),
                ('date', models.DateField()),
                ('reyting', models.IntegerField(default=0)),
                ('reyting_count', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='book/files/')),
                ('img', models.ImageField(upload_to='book/image/')),
                ('date', models.DateField()),
                ('reyting', models.IntegerField(default=0)),
                ('reyting_count', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(choices=[(1, 'going to'), (2, 'reading'), (3, 'readed')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(choices=[(1, 'going to'), (2, 'reading'), (3, 'readed')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.language'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.category'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.language'),
        ),
    ]
