# Generated by Django 4.0.1 on 2022-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_audiobook_book_category_language_historybook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
